--- # Bootstrap Webservers
- hosts: httpd
  become: yes
  tasks:
  - name: create index.htlm file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "test works"
      path: /var/www/html/index.html
  - name: check
    uri:
      url: http://127.0.0.1/index.html
      return_content: yes
    register: this
    failed_when: "'test' not in this.content"