--- # Bootstrap Webservers
- hosts: web_servers
  become: yes
  tasks:
  - name: install apache2
    yum:
      name: apache2
      state: latest
  - name: create inde.htlm file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
      line: "here is some text"
      path: /var/www/html/index.html
  - name: start apache2
    service:
      name: apache2
      state: started